// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const createElement: typeof import('better-react-dom')['createElement']
  const Fragment: typeof import('better-react-dom')['Fragment']
}
export {}
